accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as django_views

import accounts.views


app_name = 'accounts'
urlpatterns = [

    url( r'^logout$', django_views.logout, name= 'logout' ),
    url( r'^user$', accounts.views.user_page, name= 'user_page' ),
    url( r'^user/(?P<steamId>\d+)$', accounts.views.user_page, name= 'user_page' ),
    url( r'^user/(?P<steamId>\d+)/(?P<whatToShow>\w+)$', accounts.views.user_page, name= 'user_page_specify' ),

        # Add/Remove Moderator Rights
    url( r'^set_moderator/confirm/(?P<username>\w+)$', accounts.views.set_moderator_confirm, name= 'set_moderator_confirm' ),
    url( r'^set_moderator/(?P<username>\w+)$', accounts.views.set_moderator, name= 'set_moderator' ),

        # Remove Account
    url( r'^remove/confirm/(?P<username>\w+)$', accounts.views.remove_user_confirm, name= 'remove_confirm' ),
    url( r'^remove/(?P<username>\w+)$', accounts.views.remove_user, name= 'remove' ),

        # Disable Account
    url( r'^disable/confirm/(?P<username>\w+)$', accounts.views.disable_user_confirm, name= 'disable_confirm' ),
    url( r'^disable/(?P<username>\w+)$', accounts.views.disable_user, name= 'disable' ),

       # Private Messages
    url( r'^message/send/(?P<username>\w+)$', accounts.views.message_send, name= 'message_send' ),
    url( r'^message/all/$', accounts.views.message_all, name='message_all' ),
    url( r'^message/open/(?P<messageId>\w+)$', accounts.views.message_open, name= 'message_open' ),
    url( r'^message/remove_confirm/(?P<messageId>\w+)$', accounts.views.message_remove_confirm, name= 'message_remove_confirm' ),
    url( r'^message/remove/(?P<messageId>\w+)$', accounts.views.message_remove, name= 'message_remove' ),
]

steam/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

import steam.views
import social_django.urls


urlpatterns = [

    url( r'^$', steam.views.home, name= 'home' ),
    url( r'^home/(?P<whatToShow>\w+)$', steam.views.home, name= 'home_specify' ),
    url( r'^app_list$', steam.views.app_list, name= 'app_list' ),
    url( r'^find_by_id$', steam.views.find_by_id, name= 'find_by_id' ),
    url( r'^game/(?P<appId>\d+)$', steam.views.game, name= 'game' ),
    url( r'^game/(?P<appId>\d+)/(?P<whatToShow>\w+)$', steam.views.game, name= 'game_specify' ),


    url( '', include( social_django.urls, namespace= 'social' ) ),
    url( r'^accounts/', include( 'accounts.urls', namespace= 'accounts' ) ),
    url( r'^admin/', admin.site.urls ),
]


    # Serve static files when debug false
if not settings.DEBUG:
    urlpatterns += [
        url( r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT } ),
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils import timezone
from django.urls import reverse

from steam import steam_api


class Account( AbstractUser ):

    is_moderator = models.BooleanField( default= False )

    def get_url(self):
        return reverse( 'accounts:user_page', args= [ self.username ] )

    def has_moderator_rights(self):
        if self.is_staff or self.is_moderator:
            return True

        return False

    def how_many_unread_messages(self):
        return self.privatemessage_set.filter( has_been_read= False ).count()

    def get_user_social_auth(self):
        return self.social_auth.filter( provider= 'steam' )[ 0 ]

    def get_steam_extra_data(self):
        """
        :return:
            {
            'communityvisibilitystate': int, (0 or 1)
            'personaname': str,
            'personastate': int (0 or 1),
            'avatarfull': str (url),
            'steamid': str (of an int),
            'profileurl': str (url),
            'profilestate': int (0 or 1),
            'avatarmedium': str (url),
            'lastlogoff': int (unix timestamp),
            'commentpermission': int,
            'avatar': str (url)
            }
        """
        return self.get_user_social_auth().extra_data[ 'player' ]

    def get_persona_name(self):
        return self.get_steam_extra_data()[ 'personaname' ]

    def get_friends(self):
        friends = steam_api.getFriendList( self.username )

        friendsId = [ a[ 'steamid' ] for a in friends ]

        return steam_api.getPlayerSummaries( friendsId )

    def get_games_played(self):
        return steam_api.getRecentlyPlayedGames( self.username )

    def get_games_owned(self):
        return steam_api.getOwnedGames( self.username )

    def __str__(self):
        return self.get_persona_name()


class PrivateMessage( models.Model ):

    receiver = models.ForeignKey( settings.AUTH_USER_MODEL, on_delete= models.CASCADE )
    sender = models.ForeignKey( settings.AUTH_USER_MODEL, related_name= 'sender', on_delete= models.CASCADE )
    title = models.TextField( max_length= 100 )
    content = models.TextField( max_length= 500 )
    date_created = models.DateTimeField( help_text= 'Date Created', default= timezone.now )
    has_been_read = models.BooleanField( default= False )

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse( 'accounts:message_open', args= [ self.id ] )

    def get_date_created_number(self):
        """
            Time since the date it was created until the current time.
            Returns a float, useful for comparisons/sorting/etc.
        """
        diff = timezone.now() - self.date_created

        return diff.total_seconds()

    class Meta:
        ordering = [ '-date_created' ]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.html import strip_tags


class FixUserCreationForm( UserCreationForm ):
    """
        The django form has the User hard-coded (so doesn't work with custom user models)

        Just change the parts where the User is hard-coded
    """
    def clean_username(self):

        userModel = get_user_model()
        username = self.cleaned_data[ "username" ]

        try:
            userModel.objects.get( username= username )

        except userModel.DoesNotExist:
            return username

        raise forms.ValidationError( self.error_messages[ 'duplicate_username' ] )


class MyUserCreationForm( FixUserCreationForm ):

    email = forms.EmailField( required= True )

    class Meta:

        model = get_user_model()
        fields = ( 'username', 'email', 'password1', 'password2' )

    def clean_email( self ):
        """
            Check if there's already an user with that email
        """
        userModel = get_user_model()
        email = self.cleaned_data[ 'email' ]

        try:
            userModel.objects.get( email= email )

        except userModel.DoesNotExist:
            return email

        else:
            raise ValidationError( 'An account with that email already exists.' )

    def save( self, commit= True ):

        user = super( MyUserCreationForm, self ).save( commit= False )
        user.email = self.cleaned_data[ 'email' ]

        if commit:
            user.save()

        return user


class PrivateMessageForm( forms.Form ):

    title = forms.CharField( max_length= 100 )
    content = forms.CharField( max_length= 500, widget= forms.Textarea )

    def clean_title(self):
        return strip_tags( self.cleaned_data[ 'title' ] )

    def clean_content(self):
        return strip_tags( self.cleaned_data[ 'content' ] )

accounts/views.py
from django.contrib.auth import get_user_model
from django.http import Http404, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from accounts.forms import PrivateMessageForm
from accounts.models import PrivateMessage
from accounts.decorators import must_be_staff, must_be_moderator

from steam import utilities
from steam import steam_api


def user_page( request, steamId= None, whatToShow= None ):
    """
        The user page has information about an user account.
        Also where you can change some settings (like the password).

        The steam account (specified by the steam id) may or not be registered in this website.
    """
    userModel = get_user_model()

    if not steamId:
        steamId = request.GET.get( 'steamid' )

    steamId = int( steamId )
    context = {
        'steamId': steamId
    }

    try:
        user = userModel.objects.get( username= steamId )

    except userModel.DoesNotExist:
        playerSummaries = steam_api.getPlayerSummaries( [ steamId ] )

        if len( playerSummaries ) == 0:
            previous = request.GET.get( 'previous' )

            if previous:
                utilities.set_message( request, 'Account not found.' )
                return HttpResponseRedirect( previous )

            else:
                raise Http404( "Account not found." )

        context.update({
            'steamInfo': playerSummaries[ 0 ]
        })

    else:
        context.update({
            'pageUser': user,
            'unreadMessages': user.how_many_unread_messages(),
            'steamInfo': user.get_steam_extra_data()
        })

    try:
        if whatToShow == 'friends':
            context[ 'show_friends' ] = True
            context[ 'friends' ] = steam_api.getFriendsSummaries( steamId )

        elif whatToShow == 'games_owned':
            context[ 'show_games_owned' ] = True
            context[ 'games_owned' ] = steam_api.getOwnedGames( steamId )

        else:
            context[ 'show_games_played' ] = True
            context[ 'games_played' ] = steam_api.getRecentlyPlayedGames( steamId )

        # means the account is set to private
    except steam_api.SteamApiError:
        utilities.set_message( request, 'Account is private!' )

    utilities.get_message( request, context )

    return render( request, 'accounts/user_page.html', context )


@login_required
def message_send( request, username ):
    """
        Send a private message to another user.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( 'Invalid username.' )


    if request.method == 'POST':
        form = PrivateMessageForm( request.POST )

        if form.is_valid():

            title = form.cleaned_data[ 'title' ]
            content = form.cleaned_data[ 'content' ]
            message = PrivateMessage( receiver= user, sender= request.user, title= title, content= content )
            message.save()

            utilities.set_message( request, 'Message sent to {}!'.format( user ) )

            return HttpResponseRedirect( user.get_url() )

    else:
        form = PrivateMessageForm()

    context = {
        'form': form,
        'receiver': user
    }

    return render( request, 'accounts/send_message.html', context )


@login_required
def message_all( request ):

    messages = request.user.privatemessage_set.all()

    context = {
        'messages': messages
    }

    utilities.get_message( request, context )

    return render( request, 'accounts/check_messages.html', context )


@login_required
def message_open( request, messageId ):
    """
        Open a particular private message.
    """
    try:
        message = request.user.privatemessage_set.get( id= messageId )

    except PrivateMessage.DoesNotExist:
        raise Http404( "Couldn't find that message." )

    if not message.has_been_read:
        message.has_been_read = True
        message.save( update_fields= [ 'has_been_read' ] )

    context = {
        'private_message': message
    }

    return render( request, 'accounts/open_message.html', context )


@login_required
def message_remove_confirm( request, messageId ):
    """
        Confirm the message removal.
    """
    try:
        message = request.user.privatemessage_set.get( id= messageId )

    except PrivateMessage.DoesNotExist:
        raise Http404( "Didn't find the message." )

    else:
        context = {
            'private_message': message
        }

        return render( request, 'accounts/remove_message.html', context )


@login_required
def message_remove( request, messageId ):
    """
        Remove a private message.
    """
    try:
        message = request.user.privatemessage_set.get( id= messageId )

    except PrivateMessage.DoesNotExist:
        raise Http404( "Message doesn't exist." )

    message.delete()
    utilities.set_message( request, 'Message removed!' )

    return HttpResponseRedirect( reverse( 'accounts:message_all' ) )


@must_be_staff
def set_moderator_confirm( request, username ):
    """
        Confirm giving/removing moderator rights to/from an user.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        context = {
            'user_to_change': user
        }
        return render( request, 'accounts/change_moderator.html', context )


@must_be_staff
def set_moderator( request, username ):
    """
        Give/remove moderator rights from an account.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    user.is_moderator = not user.is_moderator
    user.save()

    if user.is_moderator:
        message = "'{}' is now a moderator.".format( user )

    else:
        message = "'{}' is not a moderator anymore.".format( user )

    utilities.set_message( request, message )

    return HttpResponseRedirect( user.get_url() )


@must_be_staff
def remove_user_confirm( request, username ):
    """
        Confirm an user removal.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    context = {
        'user_to_remove': user
    }

    return render( request, 'accounts/remove_user.html', context )


@must_be_staff
def remove_user( request, username ):
    """
        Remove an user account (also removes everything associated with it).
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        utilities.set_message( request, "'{}' user removed!".format( user ) )
        user.delete()

        return HttpResponseRedirect( reverse( 'home' ) )


@must_be_moderator
def disable_user_confirm( request, username ):
    """
        Confirm the enabling/disabling of an user account.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        context = {
            'user_to_disable': user
        }

        return render( request, 'accounts/disable_user.html', context )


@must_be_moderator
def disable_user( request, username ):
    """
        Enable/disable an user account.
        If the account is disabled, the user won't be able to login.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        value = not user.is_active

            # only other staff users can enable/disable staff users
        if user.is_staff:
            if request.user.is_staff:
                user.is_active = value
                user.save()

            else:
                return HttpResponseForbidden( "Can't disable a staff member." )

        else:
            user.is_active = value
            user.save()


        if value:
            message = "'{}' account is now active.".format( user )

        else:
            message = "'{}' account is now disabled.".format( user )

        utilities.set_message( request, message )

        return HttpResponseRedirect( user.get_url() )

templates/accounts/change_moderator.html
{% extends "base.html" %}
{% load accounts %}

{% block content %}

{% if user_to_change.is_moderator %}
    <h2>Remove moderator rights from {{ user_to_change|account_name }}?</h2>
{% else %}
    <h2>Give moderator rights to {{ user_to_change|account_name }}?</h2>
{% endif %}

<p>
    <a href="{% url 'accounts:set_moderator' user_to_change.username %}">Yes</a>
    <a href="{{ user_to_change.get_url }}">No</a>
</p>

{% endblock %}

templates/accounts/check_messages.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}
{% load static %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/check_messages.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tooltip.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sort_table.js' %}"></script>
{% endblock %}

{% block content %}

<h2>Private messages</h2>

{% if messages %}

    <table id="CheckMessagesTable" class="SortTable">
        <thead>
            <tr>
                <th class="SortTable-sortable">from</th>
                <th class="SortTable-sortable">title</th>
                <th class="SortTable-sortable" data-initial-sort="ascending">date</th>
            </tr>
        </thead>

        <tbody>
        {% for message in messages %}
            <tr class="clickableRow contentPreview" data-url="{{ message.get_url }}" data-content="{{ message.content|linebreaksbr|truncatewords:50 }}">
                <td data-value="{{ message.sender }}">
                    {% if not message.has_been_read %}
                        <span class="red" title="Unread message!">!</span>
                    {% endif %}

                    {{ message.sender|account_name }}
                </td>
                <td data-value="{{ message.title.strip|truncatewords:25 }}">{{ message.title|truncatewords:25 }}</td>
                <td data-value="{{ message.get_date_created_number }}">{{ message.date_created|naturaltime }}</td>
                <td><a href="{% url 'accounts:message_remove_confirm' message.id %}" title="Remove Message">X</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% else %}
    <p>No messages.</p>
{% endif %}

{% endblock %}

templates/accounts/disable_user.html
{% extends "base.html" %}
{% load accounts %}

{% block content %}

{% if user_to_disable.is_active %}
    <h2>Disable user: {{ user_to_disable|account_name }}?</h2>
{% else %}
    <h2>Enable user: {{ user_to_disable|account_name }}?</h2>
{% endif %}

<p>
    <a href="{% url 'accounts:disable' user_to_disable.username %}">Yes</a>
    <a href="{{ user_to_disable.get_url }}">No</a>
</p>

{% endblock %}

templates/accounts/open_message.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}

{% block content %}

<p>From {{ private_message.sender|account_name }} {{ private_message.date_created|naturaltime }}</p>

<h2 id="PrivateMessage-title">{{ private_message.title }}</h2>

<p>{{ private_message.content|linebreaksbr }}</p>

<a href="{% url 'accounts:message_send' private_message.sender.username %}">reply</a>
<a href="{% url 'accounts:message_all' %}">back</a>

{% endblock %}

templates/accounts/remove_message.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}

{% block content %}

<p>From {{ private_message.sender|account_name }} {{ private_message.date_created|naturaltime }}</p>

<h2 id="PrivateMessage-title">{{ private_message.title }}</h2>

<p>{{ private_message.content|linebreaksbr }}</p>


<p>Remove private message? <a href="{% url 'accounts:message_remove' private_message.id %}">Yes</a> <a href="{% url 'accounts:message_all' %}">No</a></p>

{% endblock %}

templates/accounts/remove_user.html
{% extends "base.html" %}
{% load accounts %}

{% block content %}
<h2>Remove user: {{ user_to_remove|account_name }}?</h2>

<p>
    <a href="{% url 'accounts:remove' user_to_remove.username %}">Yes</a>
    <a href="{{ user_to_remove.get_url }}">No</a>
</p>
{% endblock %}

templates/accounts/send_message.html
{% extends "base.html" %}
{% load accounts %}

{% block content %}

<h2>Send message to {{ receiver|account_name }}</h2>

{% if form.errors %}
    <p>{{ form.errors }}</p>
{% endif %}

<form method="post" action="{% url 'accounts:message_send' receiver.username %}">
    {% csrf_token %}

    <table>
        <tr>
            <td>{{ form.title.label_tag }}</td>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <td>{{ form.content.label_tag }}</td>
            <td>{{ form.content }}</td>
        </tr>
    </table>

    <input type="submit" value="send" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

templates/accounts/user_page.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}
{% load steam_filters %}
{% load static %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/sort_table.js' %}"></script>
{% endblock %}

{% block content %}

    <p><img src="{{ steamInfo.avatarfull }}" /></p>
    <h2>
        <img src="{{ steamInfo.avatar }}" /> {{ pageUser|account_name|default_if_none:steamInfo.personaname }}

        {% if pageUser %}
        <ul class="horizontalList">
            {% if user.is_moderator or user.is_staff %}
            <li>
                <a href="{% url 'accounts:disable_confirm' pageUser.username %}">
                    {% if pageUser.is_active %}
                        disable
                    {% else %}
                        enable
                    {% endif %}
                </a>
            </li>
            {% endif %}

            {% if user.is_staff %}
            <li>
                <a href="{% url 'accounts:set_moderator_confirm' pageUser.username %}">
                    {% if pageUser.is_moderator %}
                        un-mod
                    {% else %}
                        mod
                    {% endif %}
                </a>
            </li>
            <li>
                <a href="{% url 'accounts:remove_confirm' pageUser.username %}">remove</a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </h2>

    <p>Joined: {{ steamInfo.timecreated|convert_timestamp|default:"---" }}</p>
    <p>Last log off: {{ steamInfo.lastlogoff|convert_timestamp }}</p>

    {% if user.is_authenticated and pageUser %}
        <ul>
        {% if user.username == pageUser.username %}
            <li>
                <a href="{% url 'accounts:message_all' %}">See messages
                    {% if unreadMessages %}
                        (<em>{{ unreadMessages }}</em> unread)
                    {% endif %}
                </a>
            </li>
        {% else %}
            <li><a href="{% url 'accounts:message_send' steamId %}">Send private message</a></li>
        {% endif %}
        </ul>
    {% endif %}


    <ul class="horizontalList">
        <li {% if show_games_played %}class="entrySelected" {% endif %}>
            <a href="{% url 'accounts:user_page' steamId %}">games played recently</a>
        </li>
        <li {% if show_friends %}class="entrySelected" {% endif %}>
            <a href="{% url 'accounts:user_page_specify' steamId 'friends' %}">friends</a>
        </li>
        <li {% if show_games_owned %}class="entrySelected" {% endif %}>
            <a href="{% url 'accounts:user_page_specify' steamId 'games_owned' %}">games owned</a>
        </li>
    </ul>

    {% if show_friends %}
        {% if friends %}
            <table class="SortTable">
                <thead>
                    <tr>
                        <th class="SortTable-sortable">Name</th>
                        <th class="SortTable-sortable">Last Log Off</th>
                    </tr>
                </thead>

                <tbody>
                {% for friend in friends %}
                <tr>
                    <td data-value="{{ friend.personaname.strip }}"><img src="{{ friend.avatar }}" /> <a href="{% url 'accounts:user_page' friend.steamid %}">{{ friend.personaname }}</a></td>
                    <td data-value="{{ friend.lastlogoff }}">{{ friend.lastlogoff|convert_timestamp }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No friends yet.</p>
        {% endif %}

    {% elif show_games_played %}
        {% if games_played and games_played.total_count != 0 %}
            <table class="SortTable">
                <thead>
                    <tr>
                        <th class="SortTable-sortable">name</th>
                        <th class="SortTable-sortable" data-initial-sort="descending">playtime last 2 weeks</th>
                        <th class="SortTable-sortable">playtime on record</th>
                        <th>logo</th>
                    </tr>
                </thead>

                <tbody>
                {% for game in games_played.games %}
                <tr>
                    <td data-value="{{ game.name.strip }}"><a href="{% url 'game' game.appid %}" target="_blank"><img src="{{ game.img_icon_url }}" title="{{ game.name }}" /></a> {{ game.name }}</td>
                    <td data-value="{{ game.playtime_2weeks }}">{{ game.playtime_2weeks|full_time }}</td>
                    <td data-value="{{ game.playtime_forever }}">{{ game.playtime_forever|full_time }}</td>
                    <td><img src="{{ game.img_logo_url }}" /></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No games played in the last 2 weeks.</p>
        {% endif %}

    {% elif show_games_owned %}
        {% if games_owned and games_owned.game_count != 0 %}
            <p>Game count: {{ games_owned.game_count }}</p>

            <table class="SortTable">
                <thead>
                    <tr>
                        <th class="SortTable-sortable">name</th>
                        <th class="SortTable-sortable">playtime</th>
                    </tr>
                </thead>

                <tbody>
                {% for game in games_owned.games %}
                <tr>
                    <td data-value="{{ game.name.strip }}"><a href="{% url 'game' game.appid %}" target="_blank"><img src="{{ game.img_icon_url }}" title="{{ game.name }}" /></a> {{ game.name }}</td>
                    <td data-value="{{ game.playtime_forever }}">{{ game.playtime_forever|full_time }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No games owned yet.</p>
        {% endif %}
    {% endif %}

{% endblock %}