accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as django_views

import accounts.views


app_name = 'accounts'
urlpatterns = [

    url( r'^logout$', django_views.logout, name= 'logout' ),
    url( r'^user$', accounts.views.user_page, name= 'user_page' ),
    url( r'^user/(?P<steamId>\d+)$', accounts.views.user_page, name= 'user_page' ),
    url( r'^user/(?P<steamId>\d+)/(?P<whatToShow>\w+)$', accounts.views.user_page, name= 'user_page_specify' ),

        # Add/Remove Moderator Rights
    url( r'^set_moderator/confirm/(?P<username>\w+)$', accounts.views.set_moderator_confirm, name= 'set_moderator_confirm' ),
    url( r'^set_moderator/(?P<username>\w+)$', accounts.views.set_moderator, name= 'set_moderator' ),

        # Remove Account
    url( r'^remove/confirm/(?P<username>\w+)$', accounts.views.remove_user_confirm, name= 'remove_confirm' ),
    url( r'^remove/(?P<username>\w+)$', accounts.views.remove_user, name= 'remove' ),

        # Disable Account
    url( r'^disable/confirm/(?P<username>\w+)$', accounts.views.disable_user_confirm, name= 'disable_confirm' ),
    url( r'^disable/(?P<username>\w+)$', accounts.views.disable_user, name= 'disable' ),

       # Private Messages
    url( r'^message/send/(?P<username>\w+)$', accounts.views.message_send, name= 'message_send' ),
    url( r'^message/all/$', accounts.views.message_all, name='message_all' ),
    url( r'^message/open/(?P<messageId>\w+)$', accounts.views.message_open, name= 'message_open' ),
    url( r'^message/remove_confirm/(?P<messageId>\w+)$', accounts.views.message_remove_confirm, name= 'message_remove_confirm' ),
    url( r'^message/remove/(?P<messageId>\w+)$', accounts.views.message_remove, name= 'message_remove' ),
]

steam/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

import steam.views
import social_django.urls


urlpatterns = [

    url( r'^$', steam.views.home, name= 'home' ),
    url( r'^home/(?P<whatToShow>\w+)$', steam.views.home, name= 'home_specify' ),
    url( r'^app_list$', steam.views.app_list, name= 'app_list' ),
    url( r'^find_by_id$', steam.views.find_by_id, name= 'find_by_id' ),
    url( r'^game/(?P<appId>\d+)$', steam.views.game, name= 'game' ),
    url( r'^game/(?P<appId>\d+)/(?P<whatToShow>\w+)$', steam.views.game, name= 'game_specify' ),


    url( '', include( social_django.urls, namespace= 'social' ) ),
    url( r'^accounts/', include( 'accounts.urls', namespace= 'accounts' ) ),
    url( r'^admin/', admin.site.urls ),
]


    # Serve static files when debug false
if not settings.DEBUG:
    urlpatterns += [
        url( r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT } ),
    ]

templates/app_list.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/sort_table.js' %}"></script>
{% endblock %}

{% block content %}

<table class="SortTable">
    <thead>
        <tr>
            <th class="SortTable-sortable">name</th>
            <th class="SortTable-sortable" data-initial-sort="ascending">id</th>
        </tr>
    </thead>

    <tbody>
    {% for app in apps %}
    <tr>
        <td data-value="{{ app.name.strip }}"><a href="{% url 'game' app.appid %}" target="_blank">{{ app.name }}</a></td>
        <td data-value="{{ app.appid }}">{{ app.appid }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>


{% endblock %}

templates/base.html
{% load static %}
{% load accounts %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Steam</title>

    {% block scripts %}{% endblock %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>

<div id="Menu">
    <ul class="horizontalList">
        <li><a href="{% url 'home' %}">home</a></li>
        <li><a href="{% url 'app_list' %}">app list</a></li>
        <li><a href="{% url 'find_by_id' %}">find by id</a></li>
        <li>
        {% if user.is_authenticated %}
            {{ user|account_name }} ( <a href="{% url 'accounts:logout' %}?next={{ request.get_full_path|urlencode }}">logout</a> )
        {% else %}
            <a href="{% url 'social:begin' 'steam' %}?next={{ request.get_full_path|urlencode }}"><img src="http://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_large_border.png" alt="login" title="login" /></a>
        {% endif %}
        </li>
    </ul>
</div>

{% if MESSAGE %}
    <p id="Message">{{ MESSAGE }}</p>
{% endif %}

{% block content %}{% endblock %}

<footer><a href="http://steampowered.com" target="_blank">Powered by Steam</a></footer>

</body>
</html>

templates/find_by_id.html
{% extends "base.html" %}

{% block content %}

<h2>Find an account by id</h2>

<form method="GET" action="{% url 'accounts:user_page' %}">
    <table>
        <tr>
            <td>Steam id:</td>
            <td><input name="steamid" type="number" /></td>
        </tr>
    </table>

    <input type="hidden" name="previous" value="{{ request.path }}" />
    <input type="submit" value="Find" />
</form>

{% endblock %}

templates/game.html
{% extends "base.html" %}
{% load steam_filters %}
{% load static %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/sort_table.js' %}"></script>
{% endblock %}

{% block content %}

<ul class="horizontalList">
    <li {% if show_game_info %}class="entrySelected"{% endif %}>
        <a href="{% url 'game' appId %}">game info</a>
    </li>
    <li {% if show_stats %}class="entrySelected" {% endif %}>
        <a href="{% url 'game_specify' appId 'stats' %}">stats</a>
    </li>
    <li {% if show_global_achievements %}class="entrySelected"{% endif %}>
        <a href="{% url 'game_specify' appId 'global_achievements' %}">global achievements</a>
    </li>
    <li {% if show_news %}class="entrySelected" {% endif %}>
        <a href="{% url 'game_specify' appId 'news' %}">news</a>
    </li>
</ul>

{% if show_stats %}

    {% if stats %}
        <h2>Statistics</h2>

        {% if stats.stats %}
            <table class="SortTable">
                <thead>
                    <tr>
                        <th class="SortTable-sortable">name</th>
                        <th class="SortTable-sortable">value</th>
                    </tr>
                </thead>

                <tbody>
                {% for stat in stats.stats %}
                <tr>
                    <td data-value="{{ stat.name.strip }}">{{ stat.name }}</td>
                    <td data-value="{{ stat.value }}">{{ stat.value }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No stats yet.</p>
        {% endif %}

        <h2>Achievements</h2>

        {% if stats.achievements %}

            <h2>Achieved</h2>

            <table>
                <tr>
                    {% for achievement in stats.achievements %}
                        <td><img src="{{ achievement.icon }}" /> {{ achievement.displayName }}</td>

                        {% if forloop.counter|divisibleby:5 %}
                        </tr><tr>
                        {% endif %}
                    {% endfor %}
                </tr>
            </table>

        {% else %}
            <p>No achievements yet.</p>
        {% endif %}
    {% else %}
        <p>No statistics yet.</p>
    {% endif %}


{% elif show_game_info %}
    {% if game_info %}
        <h2><a href="{{ game_info.website }}">{{ game_info.name }}</a></h2>
        <img src="{{ game_info.header_image }}" />

        <p>{{ game_info.detailed_description|safe }}</p>

        <p>
            Price:
            {% if game_info.price_overview %}
                {{ game_info.price_overview.final }} {{ game_info.price_overview.currency }}
            {% else %}
                free-to-play
            {% endif %}
        </p>
        <p>
            Current players: {{ current_players }}
        </p>
        <p>
            Platforms:
            {% if game_info.platforms.windows %}windows{% endif %}
            {% if game_info.platforms.mac %}mac{% endif %}
            {% if game_info.platforms.linux %}linux{% endif %}
        </p>

        <h3>Release date</h3>
        <p>{{ game_info.release_date.date }}</p>

        <p><a href="{{ game_info.metacritic.url }}">Score: {{ game_info.metacritic.score }}</a></p>

        <h3>Categories</h3>
        <ul class="horizontalList">
        {% for category in game_info.categories %}
            <li>{{ category.description }}</li>
        {% endfor %}
        </ul>

        <h3>Genres</h3>
        <ul class="horizontalList">
        {% for genre in game_info.genres %}
            <li>{{ genre.description }}</li>
        {% endfor %}
        </ul>

        <h3>Screenshots</h3>
        <p>
        {% for screenshot in game_info.screenshots %}
            <img src="{{ screenshot.path_thumbnail }}" />
        {% endfor %}
        </p>

        <h3>Movies</h3>
        <p>
        {% for movie in game_info.movies %}
            <video width="300" height="300" controls="controls" poster="{{ movie.thumbnail }}">
                <source src="{{ movie.webm.480 }}" />
            </video>
        {% endfor %}
        </p>

        <h3>Developers</h3>
        <ul class="horizontalList">
        {% for dev in game_info.developers %}
            <li>{{ dev }}</li>
        {% endfor %}
        </ul>

        <h3>Publishers</h3>
        <ul class="horizontalList">
        {% for pub in game_info.publishers %}
            <li>{{ pub }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No game info yet.</p>
    {% endif %}

{% elif show_global_achievements %}
    {% if global_achievements %}
        <table class="SortTable">
            <thead>
                <tr>
                    <th class="SortTable-sortable">name</th>
                    <th class="SortTable-sortable" data-initial-sort="descending">percent</th>
                </tr>
            </thead>

            <tbody>
            {% for achievement in global_achievements %}
            <tr>
                <td data-value="{{ achievement.displayName.strip }}"><img src="{{ achievement.icon }}" /> {{ achievement.displayName }}</td>
                <td data-value="{{ achievement.percent }}">{{ achievement.percent|floatformat:"2" }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No global achievements yet.</p>
    {% endif %}

{% elif show_news %}
    {% if news %}
        <table class="SortTable">
            <thead>
                <tr>
                    <th class="SortTable-sortable">title</th>
                    <th>content</th>
                    <th class="SortTable-sortable">author</th>
                    <th class="SortTable-sortable" data-initial-sort="descending">date</th>
                </tr>
            </thead>

            <tbody>
            {% for new in news %}
            <tr>
                <td data-value="{{ new.title.strip }}"><a href="{{ new.url }}" target="_blank">{{ new.title }}</a></td>
                <td>{{ new.contents|safe }}</td>
                <td data-value="{{ new.author.strip }}">{{ new.author }}</td>
                <td data-value="{{ new.date }}">{{ new.date|convert_timestamp }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No news.</p>
    {% endif %}
{% endif %}


{% endblock %}

templates/game_stats.html
{% extends "base.html" %}

{% block content %}

<h1>{{ stats.gameName }}</h1>

<h2>Statistics</h2>

{% if stats.stats %}
    <table>
        <tr>
            <th>name</th>
            <th>value</th>
        </tr>
        {% for stat in stats.stats %}
        <tr>
            <td>{{ stat.name }}</td>
            <td>{{ stat.value }}</td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No stats yet.</p>
{% endif %}

<h2>Achievements</h2>

{% if stats.achievements %}
    <ul>
        {% for achievement in stats.achievements %}
            {% if achievement.achieved != 0 %}
                <li>{{ achievement.name }}</li>
            {% endif %}
        {% endfor %}
    </ul>

{% else %}
    <p>No achievements yet.</p>
{% endif %}

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load steam_filters %}
{% load static %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/sort_table.js' %}"></script>
{% endblock %}

{% block content %}

<h2>News List</h2>


{% if request.user.is_authenticated %}

    <ul class="horizontalList">
        <li {% if show_recently_played %}class="entrySelected"{% endif %}>
            <a href="{% url 'home' %}">Recently Played</a>
        </li>
        <li {% if show_owned_apps %}class="entrySelected"{% endif %}>
            <a href="{% url 'home_specify' 'owned' %}">Owned</a>
        </li>
    </ul>


    {% if news %}
        <table class="SortTable">
            <thead>
                <tr>
                    <th class="SortTable-sortable">game</th>
                    <th class="SortTable-sortable">title</th>
                    <th>content</th>
                    <th class="SortTable-sortable">author</th>
                    <th class="SortTable-sortable" data-initial-sort="descending">date</th>
                </tr>
            </thead>

            <tbody>
            {% for new in news %}
            <tr>
                <td data-value="{{ new.gameName.strip }}"><a href="{% url 'game' new.gameId %}" target="_blank"><img class="gameIcon" src="{{ new.gameIcon }}" title="{{ new.gameName }}" /></a></td>
                <td data-value="{{ new.title.strip }}"><a href="{{ new.url }}" target="_blank">{{ new.title }}</a></td>
                <td>{{ new.contents|safe }}</td>
                <td data-value="{{ new.author.strip }}">{{ new.author }}</td>
                <td data-value="{{ new.date }}">{{ new.date|convert_timestamp }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No news.</p>
    {% endif %}

{% else %}
    <p>Need to login to get the news list.</p>
{% endif %}

{% endblock %}